//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.13
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
            "MobileHub b80a7961-62cd-42f8-aa4b-e02e6a92130a aws-my-sample-app-android-v0.13";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
            Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID =
            "ap-northeast-1:ae5863dd-6ed8-419d-9cbf-06bfa6a0f88c";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
            "omnitrack-userfiles-mobilehub-1262440094";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
            Regions.fromName("ap-northeast-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
            Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
            "ap-northeast-1_tXmNuToow";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
            "3oei29hccuou1mpccp6frr6ljq";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
            "qtc9oalokk63mvbkmifrk668n2087l24mi7s0qtc05n1r5datsm";
}
